from ucd_parsing_utils import get_properties, PROP_CPP_CONV


class EmojiProperty:
    def __init__(self, codepoint, prop_type):
        self.codepoint = codepoint
        self.prop_type = PROP_CPP_CONV[prop_type]


def get_cpp_unordermap_data(props):
    start_header_data = \
        '// NOTE: This file was autogenerated via ' \
        'scripts/gen_emojiproperty_lookup.py\n' \
        '#pragma once\n\n' \
        '#include <unordered_map>\n\n' \
        '#include <auc/codepoint.hpp>\n\n' \
        '#include "property.hpp"\n\n' \
        '// https://www.unicode.org/' \
        'Public/15.0.0/ucd/emoji/emoji-data.txt\n'\
        'namespace auc {\n' \
        'namespace detail {\n\n' \
        'static std::unordered_map<codepoint, property> ' \
        'codepoint_emoji_lookup = {\n'

    header_data = ''
    num_props = len(props)
    for prop_idx in range(num_props):
        prop = props[prop_idx]
        header_data += \
            f'  {{codepoint{{{prop.codepoint}u}}, {prop.prop_type}}}'
        if prop_idx < num_props - 1:
            header_data += ',\n'

    end_header_data = \
        '\n};\n\n' \
        '} // namespace detail\n' \
        '} // namespace auc\n'

    return f'{start_header_data}{header_data}{end_header_data}'


cpp_header = get_cpp_unordermap_data(
    get_properties('emoji-data.txt', EmojiProperty)
)
with open('../src/emojiproperty_lookup.hpp', 'w') as gen_header_file:
    gen_header_file.write(cpp_header)

